// Curated, ready-to-use "skins" for the overlay widgets that have a full style
// system (Chat Bubble, Alert) — each one is a complete, already-coordinated
// set of the same fields the manual customization forms expose, so picking
// one is just applying a preset through the existing update routes rather
// than a new code path.

export const CHAT_BUBBLE_TEMPLATES = [
  {
    key: "klasik",
    label: "Klasik Hijau",
    style: {
      bubbleColor: "#ffffff",
      bubbleOpacity: 97,
      textColor: "#122e1e",
      usernameColor: "#76cc11",
      showAvatar: true,
      shape: "rounded",
      fontFamily: "Open Sans",
      fontSize: 13,
      borderWidth: 0,
      borderColor: "#76cc11",
      animation: "slide-up",
    },
  },
  {
    key: "neon",
    label: "Neon Malam",
    style: {
      bubbleColor: "#12122a",
      bubbleOpacity: 92,
      textColor: "#f5f5ff",
      usernameColor: "#00f5ff",
      showAvatar: true,
      shape: "pill",
      fontFamily: "Poppins",
      fontSize: 13,
      borderWidth: 2,
      borderColor: "#ff2fd0",
      animation: "pop",
    },
  },
  {
    key: "pastel",
    label: "Pastel Lembut",
    style: {
      bubbleColor: "#fdf2f8",
      bubbleOpacity: 96,
      textColor: "#831843",
      usernameColor: "#db2777",
      showAvatar: true,
      shape: "pill",
      fontFamily: "Comic Neue",
      fontSize: 14,
      borderWidth: 0,
      borderColor: "#f9a8d4",
      animation: "fade",
    },
  },
  {
    key: "emas",
    label: "Emas Elegan",
    style: {
      bubbleColor: "#0f0f0f",
      bubbleOpacity: 94,
      textColor: "#f5f5f5",
      usernameColor: "#facc15",
      showAvatar: true,
      shape: "rounded",
      fontFamily: "Montserrat",
      fontSize: 13,
      borderWidth: 2,
      borderColor: "#facc15",
      animation: "slide-left",
    },
  },
  {
    key: "minimalis",
    label: "Minimalis Putih",
    style: {
      bubbleColor: "#ffffff",
      bubbleOpacity: 100,
      textColor: "#111827",
      usernameColor: "#6b7280",
      showAvatar: false,
      shape: "square",
      fontFamily: "Inter",
      fontSize: 13,
      borderWidth: 1,
      borderColor: "#e5e7eb",
      animation: "fade",
    },
  },
  {
    key: "gamer",
    label: "Gamer RGB",
    style: {
      bubbleColor: "#0a0a12",
      bubbleOpacity: 90,
      textColor: "#e5e5ff",
      usernameColor: "#39ff88",
      showAvatar: true,
      shape: "rounded",
      fontFamily: "Bebas Neue",
      fontSize: 15,
      borderWidth: 2,
      borderColor: "#7c3aed",
      animation: "slide-right",
    },
  },
];

export const ALERT_TEMPLATES = [
  {
    key: "klasik",
    label: "Klasik Hijau",
    style: {
      nameColor: "#86efac",
      fontFamily: "Inter",
      fontSize: 19,
      animation: "slide-up",
      showDecorations: true,
      layout: "classic",
      bannerColor: "#1d4ed8",
      bannerHeadline: "HEY!",
      highlightColor: "#fbbf24",
      avatarPreset: "photo",
    },
  },
  {
    key: "banner-biru",
    label: "Banner Biru",
    style: {
      nameColor: "#ffffff",
      fontFamily: "Poppins",
      fontSize: 20,
      animation: "pop",
      showDecorations: true,
      layout: "banner",
      bannerColor: "#1d4ed8",
      bannerHeadline: "HEY!",
      highlightColor: "#fbbf24",
      avatarPreset: "photo",
    },
  },
  {
    key: "banner-merah",
    label: "Banner Merah Membara",
    style: {
      nameColor: "#ffffff",
      fontFamily: "Montserrat",
      fontSize: 20,
      animation: "slide-down",
      showDecorations: true,
      layout: "banner",
      bannerColor: "#dc2626",
      bannerHeadline: "WOW!",
      highlightColor: "#fde047",
      avatarPreset: "fire",
    },
  },
  {
    key: "emas-mewah",
    label: "Emas Mewah",
    style: {
      nameColor: "#fbbf24",
      fontFamily: "Montserrat",
      fontSize: 19,
      animation: "pop",
      showDecorations: false,
      layout: "classic",
      bannerColor: "#1d4ed8",
      bannerHeadline: "HEY!",
      highlightColor: "#fbbf24",
      avatarPreset: "crown",
    },
  },
  {
    key: "pesta",
    label: "Pesta Warna-Warni",
    style: {
      nameColor: "#f472b6",
      fontFamily: "Poppins",
      fontSize: 19,
      animation: "pop",
      showDecorations: true,
      layout: "classic",
      bannerColor: "#1d4ed8",
      bannerHeadline: "HEY!",
      highlightColor: "#fbbf24",
      avatarPreset: "party",
    },
  },
  {
    key: "banner-ungu",
    label: "Banner Ungu Galaksi",
    style: {
      nameColor: "#ffffff",
      fontFamily: "Bebas Neue",
      fontSize: 22,
      animation: "slide-left",
      showDecorations: true,
      layout: "banner",
      bannerColor: "#7c3aed",
      bannerHeadline: "WOAH!",
      highlightColor: "#22d3ee",
      avatarPreset: "star",
    },
  },
];
