// Curated, ready-to-use "skins" for the overlay widgets that have a full style
// system (Chat Bubble, Alert) — each one is a complete, already-coordinated
// set of the same fields the manual customization forms expose, so picking
// one is just applying a preset through the existing update routes rather
// than a new code path.

export const CHAT_BUBBLE_TEMPLATES = [
  {
    key: "klasik",
    label: "Klasik Hijau",
    style: {
      bubbleColor: "#ffffff",
      bubbleOpacity: 97,
      textColor: "#122e1e",
      usernameColor: "#76cc11",
      showAvatar: true,
      shape: "rounded",
      fontFamily: "Open Sans",
      fontSize: 13,
      borderWidth: 0,
      borderColor: "#76cc11",
      animation: "slide-up",
    },
  },
  {
    key: "neon",
    label: "Neon Malam",
    style: {
      bubbleColor: "#12122a",
      bubbleOpacity: 92,
      textColor: "#f5f5ff",
      usernameColor: "#00f5ff",
      showAvatar: true,
      shape: "pill",
      fontFamily: "Poppins",
      fontSize: 13,
      borderWidth: 2,
      borderColor: "#ff2fd0",
      animation: "pop",
    },
  },
  {
    key: "pastel",
    label: "Pastel Lembut",
    style: {
      bubbleColor: "#fdf2f8",
      bubbleOpacity: 96,
      textColor: "#831843",
      usernameColor: "#db2777",
      showAvatar: true,
      shape: "pill",
      fontFamily: "Comic Neue",
      fontSize: 14,
      borderWidth: 0,
      borderColor: "#f9a8d4",
      animation: "fade",
    },
  },
  {
    key: "emas",
    label: "Emas Elegan",
    style: {
      bubbleColor: "#0f0f0f",
      bubbleOpacity: 94,
      textColor: "#f5f5f5",
      usernameColor: "#facc15",
      showAvatar: true,
      shape: "rounded",
      fontFamily: "Montserrat",
      fontSize: 13,
      borderWidth: 2,
      borderColor: "#facc15",
      animation: "slide-left",
    },
  },
  {
    key: "minimalis",
    label: "Minimalis Putih",
    style: {
      bubbleColor: "#ffffff",
      bubbleOpacity: 100,
      textColor: "#111827",
      usernameColor: "#6b7280",
      showAvatar: false,
      shape: "square",
      fontFamily: "Inter",
      fontSize: 13,
      borderWidth: 1,
      borderColor: "#e5e7eb",
      animation: "fade",
    },
  },
  {
    key: "gamer",
    label: "Gamer RGB",
    style: {
      bubbleColor: "#0a0a12",
      bubbleOpacity: 90,
      textColor: "#e5e5ff",
      usernameColor: "#39ff88",
      showAvatar: true,
      shape: "rounded",
      fontFamily: "Bebas Neue",
      fontSize: 15,
      borderWidth: 2,
      borderColor: "#7c3aed",
      animation: "slide-right",
    },
  },
];

export const ALERT_TEMPLATES = [
  {
    key: "klasik",
    label: "Klasik Hijau",
    style: {
      nameColor: "#86efac",
      fontFamily: "Inter",
      fontSize: 19,
      animation: "slide-up",
      showDecorations: true,
      layout: "classic",
      bannerColor: "#1d4ed8",
      bannerHeadline: "HEY!",
      highlightColor: "#fbbf24",
      avatarPreset: "photo",
    },
  },
  {
    key: "banner-biru",
    label: "Banner Biru",
    style: {
      nameColor: "#ffffff",
      fontFamily: "Poppins",
      fontSize: 20,
      animation: "pop",
      showDecorations: true,
      layout: "banner",
      bannerColor: "#1d4ed8",
      bannerHeadline: "HEY!",
      highlightColor: "#fbbf24",
      avatarPreset: "photo",
    },
  },
  {
    key: "banner-merah",
    label: "Banner Merah Membara",
    style: {
      nameColor: "#ffffff",
      fontFamily: "Montserrat",
      fontSize: 20,
      animation: "slide-down",
      showDecorations: true,
      layout: "banner",
      bannerColor: "#dc2626",
      bannerHeadline: "WOW!",
      highlightColor: "#fde047",
      avatarPreset: "fire",
    },
  },
  {
    key: "emas-mewah",
    label: "Emas Mewah",
    style: {
      nameColor: "#fbbf24",
      fontFamily: "Montserrat",
      fontSize: 19,
      animation: "pop",
      showDecorations: false,
      layout: "classic",
      bannerColor: "#1d4ed8",
      bannerHeadline: "HEY!",
      highlightColor: "#fbbf24",
      avatarPreset: "crown",
    },
  },
  {
    key: "pesta",
    label: "Pesta Warna-Warni",
    style: {
      nameColor: "#f472b6",
      fontFamily: "Poppins",
      fontSize: 19,
      animation: "pop",
      showDecorations: true,
      layout: "classic",
      bannerColor: "#1d4ed8",
      bannerHeadline: "HEY!",
      highlightColor: "#fbbf24",
      avatarPreset: "party",
    },
  },
  {
    key: "banner-ungu",
    label: "Banner Ungu Galaksi",
    style: {
      nameColor: "#ffffff",
      fontFamily: "Bebas Neue",
      fontSize: 22,
      animation: "slide-left",
      showDecorations: true,
      layout: "banner",
      bannerColor: "#7c3aed",
      bannerHeadline: "WOAH!",
      highlightColor: "#22d3ee",
      avatarPreset: "star",
    },
  },
];

// Same "skin family" names as the Chat Bubble/Alert templates above, so a
// host who picks "Neon Malam" everywhere gets a visually matching set.
export const LEADERBOARD_TEMPLATES = [
  {
    key: "klasik",
    label: "Klasik Hijau",
    style: {
      cardStyle: "transparent",
      panelColor: "#000000",
      panelOpacity: 55,
      headerColor: "#ffffff",
      rankColor: "#4ade80",
      nameColor: "#ffffff",
      amountColor: "#ffffff",
      fontFamily: "Inter",
      fontSize: 14,
    },
  },
  {
    key: "neon",
    label: "Neon Malam",
    style: {
      cardStyle: "panel",
      panelColor: "#12122a",
      panelOpacity: 88,
      headerColor: "#f5f5ff",
      rankColor: "#00f5ff",
      nameColor: "#f5f5ff",
      amountColor: "#ff2fd0",
      fontFamily: "Poppins",
      fontSize: 14,
    },
  },
  {
    key: "pastel",
    label: "Pastel Lembut",
    style: {
      cardStyle: "panel",
      panelColor: "#fdf2f8",
      panelOpacity: 92,
      headerColor: "#831843",
      rankColor: "#db2777",
      nameColor: "#831843",
      amountColor: "#db2777",
      fontFamily: "Comic Neue",
      fontSize: 15,
    },
  },
  {
    key: "emas",
    label: "Emas Elegan",
    style: {
      cardStyle: "panel",
      panelColor: "#0f0f0f",
      panelOpacity: 90,
      headerColor: "#facc15",
      rankColor: "#facc15",
      nameColor: "#f5f5f5",
      amountColor: "#facc15",
      fontFamily: "Montserrat",
      fontSize: 14,
    },
  },
  {
    key: "minimalis",
    label: "Minimalis Putih",
    style: {
      cardStyle: "panel",
      panelColor: "#ffffff",
      panelOpacity: 96,
      headerColor: "#111827",
      rankColor: "#6b7280",
      nameColor: "#111827",
      amountColor: "#111827",
      fontFamily: "Inter",
      fontSize: 14,
    },
  },
  {
    key: "gamer",
    label: "Gamer RGB",
    style: {
      cardStyle: "panel",
      panelColor: "#0a0a12",
      panelOpacity: 86,
      headerColor: "#e5e5ff",
      rankColor: "#39ff88",
      nameColor: "#e5e5ff",
      amountColor: "#7c3aed",
      fontFamily: "Bebas Neue",
      fontSize: 16,
    },
  },
];

export const LIKEATHON_TEMPLATES = [
  {
    key: "klasik",
    label: "Klasik Hijau",
    style: {
      panelColor: "#ffffff",
      panelOpacity: 97,
      titleColor: "#122e1e",
      titleIcon: "❤️",
      rankColor: "#76cc11",
      nameColor: "#122e1e",
      valColor: "#122e1e",
      fontFamily: "Open Sans",
      fontSize: 13,
    },
  },
  {
    key: "neon",
    label: "Neon Malam",
    style: {
      panelColor: "#12122a",
      panelOpacity: 90,
      titleColor: "#f5f5ff",
      titleIcon: "⚡",
      rankColor: "#00f5ff",
      nameColor: "#f5f5ff",
      valColor: "#ff2fd0",
      fontFamily: "Poppins",
      fontSize: 13,
    },
  },
  {
    key: "pastel",
    label: "Pastel Lembut",
    style: {
      panelColor: "#fdf2f8",
      panelOpacity: 96,
      titleColor: "#831843",
      titleIcon: "💕",
      rankColor: "#db2777",
      nameColor: "#831843",
      valColor: "#db2777",
      fontFamily: "Comic Neue",
      fontSize: 14,
    },
  },
  {
    key: "emas",
    label: "Emas Elegan",
    style: {
      panelColor: "#0f0f0f",
      panelOpacity: 94,
      titleColor: "#facc15",
      titleIcon: "👑",
      rankColor: "#facc15",
      nameColor: "#f5f5f5",
      valColor: "#facc15",
      fontFamily: "Montserrat",
      fontSize: 13,
    },
  },
  {
    key: "minimalis",
    label: "Minimalis Putih",
    style: {
      panelColor: "#ffffff",
      panelOpacity: 100,
      titleColor: "#111827",
      titleIcon: "🤍",
      rankColor: "#6b7280",
      nameColor: "#111827",
      valColor: "#111827",
      fontFamily: "Inter",
      fontSize: 13,
    },
  },
  {
    key: "gamer",
    label: "Gamer RGB",
    style: {
      panelColor: "#0a0a12",
      panelOpacity: 90,
      titleColor: "#e5e5ff",
      titleIcon: "🎮",
      rankColor: "#39ff88",
      nameColor: "#e5e5ff",
      valColor: "#7c3aed",
      fontFamily: "Bebas Neue",
      fontSize: 15,
    },
  },
];

export const WAKTU_TEMPLATES = [
  {
    key: "klasik",
    label: "Klasik Hijau",
    style: {
      panelColor: "#000000",
      panelOpacity: 55,
      labelColor: "#ffffff",
      clockColor: "#ffffff",
      addedColor: "#4ade80",
      fontFamily: "Open Sans",
      clockSize: 52,
    },
  },
  {
    key: "neon",
    label: "Neon Malam",
    style: {
      panelColor: "#12122a",
      panelOpacity: 90,
      labelColor: "#f5f5ff",
      clockColor: "#00f5ff",
      addedColor: "#ff2fd0",
      fontFamily: "Poppins",
      clockSize: 52,
    },
  },
  {
    key: "pastel",
    label: "Pastel Lembut",
    style: {
      panelColor: "#fdf2f8",
      panelOpacity: 95,
      labelColor: "#831843",
      clockColor: "#831843",
      addedColor: "#db2777",
      fontFamily: "Comic Neue",
      clockSize: 50,
    },
  },
  {
    key: "emas",
    label: "Emas Elegan",
    style: {
      panelColor: "#0f0f0f",
      panelOpacity: 92,
      labelColor: "#facc15",
      clockColor: "#facc15",
      addedColor: "#facc15",
      fontFamily: "Montserrat",
      clockSize: 52,
    },
  },
  {
    key: "minimalis",
    label: "Minimalis Putih",
    style: {
      panelColor: "#ffffff",
      panelOpacity: 98,
      labelColor: "#6b7280",
      clockColor: "#111827",
      addedColor: "#16a34a",
      fontFamily: "Inter",
      clockSize: 50,
    },
  },
  {
    key: "gamer",
    label: "Gamer RGB",
    style: {
      panelColor: "#0a0a12",
      panelOpacity: 90,
      labelColor: "#e5e5ff",
      clockColor: "#39ff88",
      addedColor: "#7c3aed",
      fontFamily: "Bebas Neue",
      clockSize: 56,
    },
  },
];

export const MILESTONE_TEMPLATES = [
  {
    key: "klasik",
    label: "Klasik Hijau",
    style: {
      panelColor: "#000000",
      panelOpacity: 55,
      labelColor: "#ffffff",
      countColor: "#4ade80",
      fillColor: "#4ade80",
      reachedColor: "#facc15",
      fontFamily: "Open Sans",
    },
  },
  {
    key: "neon",
    label: "Neon Malam",
    style: {
      panelColor: "#12122a",
      panelOpacity: 90,
      labelColor: "#f5f5ff",
      countColor: "#00f5ff",
      fillColor: "#00f5ff",
      reachedColor: "#ff2fd0",
      fontFamily: "Poppins",
    },
  },
  {
    key: "pastel",
    label: "Pastel Lembut",
    style: {
      panelColor: "#fdf2f8",
      panelOpacity: 95,
      labelColor: "#831843",
      countColor: "#db2777",
      fillColor: "#db2777",
      reachedColor: "#eab308",
      fontFamily: "Comic Neue",
    },
  },
  {
    key: "emas",
    label: "Emas Elegan",
    style: {
      panelColor: "#0f0f0f",
      panelOpacity: 92,
      labelColor: "#facc15",
      countColor: "#facc15",
      fillColor: "#facc15",
      reachedColor: "#fef08a",
      fontFamily: "Montserrat",
    },
  },
  {
    key: "minimalis",
    label: "Minimalis Putih",
    style: {
      panelColor: "#ffffff",
      panelOpacity: 98,
      labelColor: "#111827",
      countColor: "#16a34a",
      fillColor: "#16a34a",
      reachedColor: "#d97706",
      fontFamily: "Inter",
    },
  },
  {
    key: "gamer",
    label: "Gamer RGB",
    style: {
      panelColor: "#0a0a12",
      panelOpacity: 90,
      labelColor: "#e5e5ff",
      countColor: "#39ff88",
      fillColor: "#39ff88",
      reachedColor: "#7c3aed",
      fontFamily: "Bebas Neue",
    },
  },
];

export const WISHLIST_TEMPLATES = [
  {
    key: "klasik",
    label: "Klasik Hijau",
    style: {
      cardStyle: "transparent",
      panelColor: "#000000",
      panelOpacity: 55,
      headerColor: "#ffffff",
      titleColor: "#ffffff",
      pctColor: "#4ade80",
      doneColor: "#fbbf24",
      fillColor: "#4ade80",
      fontFamily: "Inter",
      fontSize: 16,
    },
  },
  {
    key: "neon",
    label: "Neon Malam",
    style: {
      cardStyle: "panel",
      panelColor: "#12122a",
      panelOpacity: 90,
      headerColor: "#f5f5ff",
      titleColor: "#f5f5ff",
      pctColor: "#00f5ff",
      doneColor: "#ff2fd0",
      fillColor: "#00f5ff",
      fontFamily: "Poppins",
      fontSize: 16,
    },
  },
  {
    key: "pastel",
    label: "Pastel Lembut",
    style: {
      cardStyle: "panel",
      panelColor: "#fdf2f8",
      panelOpacity: 95,
      headerColor: "#831843",
      titleColor: "#831843",
      pctColor: "#db2777",
      doneColor: "#eab308",
      fillColor: "#db2777",
      fontFamily: "Comic Neue",
      fontSize: 17,
    },
  },
  {
    key: "emas",
    label: "Emas Elegan",
    style: {
      cardStyle: "panel",
      panelColor: "#0f0f0f",
      panelOpacity: 92,
      headerColor: "#facc15",
      titleColor: "#f5f5f5",
      pctColor: "#facc15",
      doneColor: "#fef08a",
      fillColor: "#facc15",
      fontFamily: "Montserrat",
      fontSize: 16,
    },
  },
  {
    key: "minimalis",
    label: "Minimalis Putih",
    style: {
      cardStyle: "panel",
      panelColor: "#ffffff",
      panelOpacity: 98,
      headerColor: "#6b7280",
      titleColor: "#111827",
      pctColor: "#16a34a",
      doneColor: "#d97706",
      fillColor: "#16a34a",
      fontFamily: "Inter",
      fontSize: 16,
    },
  },
  {
    key: "gamer",
    label: "Gamer RGB",
    style: {
      cardStyle: "panel",
      panelColor: "#0a0a12",
      panelOpacity: 90,
      headerColor: "#e5e5ff",
      titleColor: "#e5e5ff",
      pctColor: "#39ff88",
      doneColor: "#7c3aed",
      fillColor: "#39ff88",
      fontFamily: "Bebas Neue",
      fontSize: 18,
    },
  },
];

// Shared "white card" look across Likes/Followers/Share/Gift — one template
// picker instead of four near-identical ones.
export const TAG_TEMPLATES = [
  {
    key: "klasik",
    label: "Klasik Hijau",
    style: { bgColor: "#ffffff", bgOpacity: 97, textColor: "#122e1e", accentColor: "#76cc11", fontFamily: "Open Sans", fontSize: 20 },
  },
  {
    key: "neon",
    label: "Neon Malam",
    style: { bgColor: "#12122a", bgOpacity: 92, textColor: "#f5f5ff", accentColor: "#00f5ff", fontFamily: "Poppins", fontSize: 20 },
  },
  {
    key: "pastel",
    label: "Pastel Lembut",
    style: { bgColor: "#fdf2f8", bgOpacity: 96, textColor: "#831843", accentColor: "#db2777", fontFamily: "Comic Neue", fontSize: 21 },
  },
  {
    key: "emas",
    label: "Emas Elegan",
    style: { bgColor: "#0f0f0f", bgOpacity: 94, textColor: "#f5f5f5", accentColor: "#facc15", fontFamily: "Montserrat", fontSize: 20 },
  },
  {
    key: "minimalis",
    label: "Minimalis Putih",
    style: { bgColor: "#ffffff", bgOpacity: 100, textColor: "#111827", accentColor: "#6b7280", fontFamily: "Inter", fontSize: 20 },
  },
  {
    key: "gamer",
    label: "Gamer RGB",
    style: { bgColor: "#0a0a12", bgOpacity: 90, textColor: "#e5e5ff", accentColor: "#39ff88", fontFamily: "Bebas Neue", fontSize: 22 },
  },
];
